### ISSUE TITLE
Don't know how to use this

### ISSUE THREAD

**Issue by leninberg** [lamourj/sbbot#1]
I installed the bot following the link provided. Then I wrote /start
Then later I wrote /unique. It doesn't do anything... Some help would be appreciated, thanks

**Comment by lamourj** [comment]
Can you give more details about what you tried? Did you indeed registered your bot and changed the API token ?
Any error message is appreciated too.

**Comment by leninberg** [comment]
I simply press on the link mentioned
"You can just click on this link..."
The browser tells me to open the link with Telegram, I agree, and then the bot appears on Telegram.
If I write /start or /unique, It doesn't do anything, I don't get any error message.
About the registering or the API token I didn't do anything. I thought the installation was simply following the link. Can you elaborate a bit on that? I have access to a computer with linux installed if necessary. Thank you.

**Comment by vwvw** [comment]
We are not running our bot instance anymore. You will need to setup your own one as explained in the readMe. You will need a server running 24/7 if you want to be able to use it at any time.

**Comment by leninberg** [comment]
Thank you.
